name: midjourney_client
description: > 
  Unofficial midjourney client that gives you possibility to generates images! 
  Now, it utilizes the Discord API to communicate with the bot.
version: 0.3.3-alpha
repository: https://github.com/hawkkiller/midjourney-client

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  snowflaker: ^1.1.0
  http: ^1.0.0
  meta: ^1.9.1
  ws: ^0.0.7-dev
  path: ^1.8.1

dev_dependencies:
  sizzle_lints: ^1.0.10
  test: ^1.21.0
